config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  root to: 'public#index'

  resources :contatos, only: [:new, :create]

  get '/sobre', to: 'apresentacao#sobre'

  resources :rastreamentos, only: [:index, :create]

  mount  Sidekiq::Web, at: '/sidekiq'

  match '*a', :to => 'errors#routing', via: :get

end

app/models/contato.rb
class Contato < ActiveRecord::Base
  validates_presence_of :nome
  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
  validates :email, uniqueness: true
end

app/models/rastreamento.rb
class Rastreamento < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def render_404(exception = nil)
    if exception
      logger.info "Rendering 404: #{exception.message}"
    end

    render :file => "#{Rails.root}/public/404.html", :status => 404
  end
end

app/controllers/apresentacao_controller.rb
class ApresentacaoController < ApplicationController

  def home
  end

  def sobre
  end

end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  before_action :set_contato, only: [:show, :edit, :update, :destroy]

  # GET /contatos
  # GET /contatos.json
  def index
    @contatos = Contato.all
  end

  # GET /contatos/1
  # GET /contatos/1.json
  def show
  end

  # GET /contatos/new
  def new
    @contato = Contato.new
  end

  # GET /contatos/1/edit
  def edit
  end

  # POST /contatos
  # POST /contatos.json
  def create
    @contato = Contato.new(contato_params)

    respond_to do |format|
      if @contato.save
        format.html { redirect_to new_contato_path, notice: 'O contato foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @contato }
      else
        format.html { render :new }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contatos/1
  # PATCH/PUT /contatos/1.json
  def update
    respond_to do |format|
      if @contato.update(contato_params)
        format.html { redirect_to @contato, notice: 'Contato was successfully updated.' }
        format.json { render :show, status: :ok, location: @contato }
      else
        format.html { render :edit }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contatos/1
  # DELETE /contatos/1.json
  def destroy
    @contato.destroy
    respond_to do |format|
      format.html { redirect_to contatos_url, notice: 'Contato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contato
      @contato = Contato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contato_params
      params.require(:contato).permit(:nome, :email)
    end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def routing
    render_404
  end
end

app/controllers/rastreamentos_controller.rb
class RastreamentosController < ApplicationController
  before_action :set_rastreamento, only: [:show, :edit, :update, :destroy]

  skip_before_action :verify_authenticity_token

  # GET /rastreamentos
  # GET /rastreamentos.json
  def index
    @rastreamentos = Rastreamento.all.order("data_hora desc").limit(50)
  end

  # GET /rastreamentos/1
  # GET /rastreamentos/1.json
  def show
  end

  # GET /rastreamentos/new
  def new
    @rastreamento = Rastreamento.new
  end

  # GET /rastreamentos/1/edit
  def edit
  end

  # POST /rastreamentos
  # POST /rastreamentos.json
  def create
    mensagem = validate_params

    if !mensagem.empty?
      return respond_to do |format|
        format.json { render json: mensagem, status: :bad_request }
      end
    end

    @rastreamento = Rastreamento.new(rastreamento_params)

    respond_to do |format|
      if ENV['USE_SIDEKIQ'] == "true"
        RastreamentoWorker.perform_async(rastreamento_params)
        format.json { render :nothing => true, status: :created }
      else
        if @rastreamento.save
          format.html { redirect_to @rastreamento, notice: 'Rastreamento was successfully created.' }
          format.json { render :nothing => true, status: :created }
        else
          format.html { render :new }
          format.json { render json: @rastreamento.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /rastreamentos/1
  # PATCH/PUT /rastreamentos/1.json
  def update
    respond_to do |format|
      if @rastreamento.update(rastreamento_params)
        format.html { redirect_to @rastreamento, notice: 'Rastreamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @rastreamento }
      else
        format.html { render :edit }
        format.json { render json: @rastreamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rastreamentos/1
  # DELETE /rastreamentos/1.json
  def destroy
    @rastreamento.destroy
    respond_to do |format|
      format.html { redirect_to rastreamentos_url, notice: 'Rastreamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_rastreamento
    @rastreamento = Rastreamento.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def rastreamento_params
    params.require(:rastreamento).permit(:visitante, :url, :titulo, :data_hora)
  end

  def validate_params
    mensagem = []
    mensagem << 'Parâmetro visitante inexistente.' if params[:rastreamento][:visitante].nil? || params[:rastreamento][:visitante].empty?
    mensagem << 'Parâmetro url inexistente.' if params[:rastreamento][:url].nil? || params[:rastreamento][:url].empty?
    mensagem << 'Parâmetro título inexistente.' if params[:rastreamento][:titulo].nil? || params[:rastreamento][:titulo].empty?
    mensagem << 'Parâmetro data/hora inexistente.' if params[:rastreamento][:data_hora].nil? || params[:rastreamento][:data_hora].empty?
    mensagem_formatted = format_message(mensagem)
    return {mensagem: mensagem_formatted}.to_json if !mensagem.empty?
    ''
  end

  def format_message(mensagem)
    msg = ''
    mensagem.each_with_index do |m, index|
      msg += m
      msg += " " if index < mensagem.count - 1
    end
    msg
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for :title, page_title.to_s
  end
end

app/views/contatos/_form.html.erb
<% content_for :header do %>
    <%= render :partial => 'layouts/navbar', :locals => {id: :contato} %>
<% end %>

<div class="col-md-4 col-md-offset-4">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title"><%= panel_title %></h3>
    </div>
    <div class="panel-body">
      <%= simple_form_for @contato do |f| %>
          <%= f.error_notification %>
          <%= f.input :nome, autofocus: true %>
          <%= f.input :email %>
          <%= f.button :submit, 'Criar Contato', class: "btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

<% content_for :javascript do %>
<% end %>

app/views/contatos/new.html.erb
<% title "Contato" %>

<%= render :partial => 'form', :locals => {panel_title: 'Preencha um Novo Contato'} %>

app/views/layouts/_alert.html.erb
<% flash.each do |name, msg| %>
    <% unless msg.blank? %>
        <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= msg %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_header.html.erb
<% id ||= :none %>
<header>
  <nav class="navbar navbar-inverse navbar-fixed-top sticky" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle pull-right" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse navbar-ex1-collapse" role="navigation">
        <ul class="nav navbar-nav navbar-right">
          <%= yield :navbar_list %>
        </ul>
      </div>
    </div>
  </nav>
</header>
<script>
    jQuery(function () {
        $('#<%= id %>').addClass('active');
    });
</script>

app/views/layouts/_navbar.erb
<% content_for :navbar_list do %>
    <li id="contato"><%= link_to "Contato", new_contato_path %></li>
    <li id="relatorio"><%= link_to "Relatório de Rastreamento", rastreamentos_path %></li>
<% end %>

<%= render :partial => 'layouts/header',
           :locals => {id: id} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title><%= yield(:title) %></title>

  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <!--[if lt IE 9]>
  <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <%= yield :stylesheet %>

  <%= csrf_meta_tags %>
</head>
<body class="fixed_top">
<%= yield :header %>

<div class="container" style="padding-top: 70px;">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <%= render :partial => 'layouts/alert' %>
    </div>
  </div>
</div>
<%= yield %>

<%= yield :javascript %>
</body>
</html>

app/views/rastreamentos/index.html.erb
<% title "Relatório de Rastreamento" %>

<% content_for :stylesheet do %>
<% end %>

<% content_for :header do %>
    <%= render :partial => 'layouts/navbar', :locals => {id: :relatorio} %>
<% end %>

<div class="container" style="padding-top: 70px;">
  <h1>Lista os últimos <%= @rastreamentos.count %> acessos rastreados</h1>

  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-info">
        <div class="panel-heading clearfix">
          <h3 class="panel-title pull-left">Acessos Rastreados</h3>
        </div>
        <div class="panel-body">
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
              <tr>
                <th>Visitante</th>
                <th>URL visitada</th>
                <th>Título da Janela</th>
                <th>Data/Hora</th>
              </tr>
              </thead>
              <tbody>
              <% @rastreamentos.each do |rastreamento| %>
                  <tr>
                    <td><%= rastreamento.visitante %></td>
                    <td><%= rastreamento.url %></td>
                    <td><%= rastreamento.titulo %></td>
                    <td><%= rastreamento.data_hora.strftime("%d/%m/%Y %H:%M:%S") %></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :javascript do %>
<% end %>